# Generated by Django 4.1.7 on 2023-03-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_t_ask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_ask',
        ),
    ]
