# Generated by Django 4.1.7 on 2023-03-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_delete_t_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2003-04-09'),
            preserve_default=False,
        ),
    ]
